# Use official Node.js LTS image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json & package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy backend code
COPY . .

# Expose port your app runs on
EXPOSE 5000

# Start app
CMD ["npm", "run", "devStart"]
